export const APP_LOAD = 'APP_LOAD';
export const APP_LOADED = 'APP_LOADED';
export const SET_PAGE = 'SET_PAGE';

// AYSNC
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

// HOME
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

// RESTAURANT
export const RESTAURANT_SUBMITTED = 'RESTAURANT_SUBMITTED';
export const RESTAURANT_PAGE_LOADED = 'RESTAURANT_PAGE_LOADED';
export const RESTAURANT_PAGE_UNLOADED = 'RESTAURANT_PAGE_UNLOADED';

// TAG
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER';
